set test_name "Ping example.com"

send "\r"
expect #

send "ping example.com -c 1 -W 8\r"

expect {
    "0% packet loss" {
        pass $test_name
    }
    "100% packet loss" {
        fail "$test_name $expect_out(buffer)"
    }
    "#" {
        unresolved "$test_name returned prompt unexpectedly: $expect_out(buffer)"
    }
    timeout {
        fail "$test_name timed out: $expect_out(buffer)" 
    }
}
