
FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
	&& apt-get install -y apt dpkg apt-utils ca-certificates \
	&& apt-get upgrade -y \
	&& apt-get install -y \
        dumb-init \
	    qemu-kvm \
        libvirt-dev \
        libvirt-daemon-system \
        bridge-utils \
        dnsmasq \
        net-tools \
        virtinst \
        dejagnu \
        linux-image-$(uname -r) \
	&& rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["bash", "-c", "chown root:kvm /dev/kvm; libvirtd& virtlogd& /bin/bash"]
